### PR TITLE
Sleep timer count down: improve visual clue when enabled #199

### PR DESCRIPTION
**Pull request by skynetua**
Works ok for me, please review.

### CODE REVIEW

**Comment by Ph1b** [comment]
It leaks the activity.

**Comment by Ph1b** [comment]
Okay, what happens is you call showTimerCountdown in onStart. You also call it in onCreate. And you call it in onSleepStateChanged. When there is a new activity (or you rotate the device), you call that method, which creates (if the sleep timer is active) 3 instances of CountDownTimer. Each of these instances hold a reference to a TextView. This textView hols a reference to the context. This context holds a reference to the activity.
In onStop you cancel the CountdownTimer. But just the last one. So all the messages referring to the internal handler of the CountdownTimer stay. And thus the whole view hierarchy is being leaked.

**Comment by skynetua** [comment]
Ok, I can remove call from onCreate - it is redundant. I thought onSleepStateChanged is called only when service set\unset timer. Why it is called while activity starting?

**Comment by Ph1b** [comment]
It isnt. I merged it and applied the fix. Thanks a lot!

**Pull request merged**
